### ISSUE TITLE
Text capitalization and navigation bar

### ISSUE THREAD

**Issue by j0sefali** [zeon-studio/nextplate#18]
There should be a way to disable the text capitalization in buttons and other elements that use it so that other languages can be supported.

If you open the navigation menu on a small screen and then enlarge the window, the menu remains open. There should also be a way to disable the header and footer on selected pages.

**Comment by tfsomrat** [comment]
Hey @JosefAl1, I want to let you know that this is a starter template. You need to modify this template as you need to your project. thanks
