### ISSUE TITLE
404 for png images in nextConfig output: 'export' mode

### ISSUE THREAD

**Issue by spcfx** [zeon-studio/nextplate#2]
Fantastic template, but when I had to use it outside vercel with the `output: 'export'` configuration in next.config.js all the png images are broken, svg files instead are rendered correctly.

**Comment by tfsomrat** [comment]
Hi @sp-cfx, thanks for choosing our theme. this is expected behavior actually. please follow the instructions to get your result https://nextjs.org/docs/app/building-your-application/deploying/static-exports

**Comment by spcfx** [comment]
Thank you, I'm new to Nextjs so I'll check the docs better then
