### ISSUE TITLE
npm or yarn nor any dependencies are not installing at all

### ISSUE THREAD

**Issue by nirtutac123** [zeon-studio/nextplate#21]
(Windows user)Seems like i have good internet connection of 210mbps . But any installation process of the dependencies after cloning of the project doesn't work at all. 
npm install shows this for hours(image attached below) and yarn install shows you have trouble with your internet connection.

Am i doing something wrong  here?
<img width="479" alt="Screenshot 2024-01-02 160225" src="https://github.com/zeon-studio/nextplate/assets/117327381/a962b7da-95c1-494c-91e4-9d81a06991ac">

**Comment by tfsomrat** [comment]
Hi @nirtutac123, I think you have an issue with your machine. you can try some different projects to check if it's working. thanks

**Comment by nirtutac123** [comment]
yes i did everything. Cloned again, restart laptop.
After 1 day, somehow it works now. Thank you.
