### ISSUE TITLE
Checkbox Doesn't Shift Left When Initial Theme is Dark, but Theme Switches Successfully

### ISSUE THREAD

**Issue by impiia** [zeon-studio/nextplate#28]
If the initial theme is dark, the checkbox does not shift to the left when the theme is toggled, even though the theme changes as expected. This issue does not occur if the initial theme is light. Changing defaultChecked to checked in the ThemeSwitcher component resolves the issue.

**Comment by zatrudnitel** [comment]
I noticed this bug too
