### ISSUE TITLE
Error: "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists"

### ISSUE THREAD

**Issue by noams24** [zeon-studio/nextplate#4]
![Untitled](https://github.com/zeon-studio/nextplate/assets/80849999/cbc45ca6-fc25-4d2a-ba44-773a98dedb5b)
Why every file has this error?

**Comment by tfsomrat** [comment]
This is not an issue. Install dependencies by running `yarn`, and all the warning will be gone. thank you.
